@startuml
class Player {
    - position_x: int
    - position_y: int
    - state: state_t
    + Player_movement(direction_t dir): bool
    + Player_init(): void
    + Player_start(): void
    + Player_stop():void
    + Player_getHP(): int
    + Player_setHP(int HP): void
    + Player_hit(): bool
    + Player_get_pos(): Coordinates
    - run(event_t event): void
}
class Map {
    - game_map: char **
    + Map_init(): void
    + Map_print(): void
    + Map_set_case(Coordinates newPos, Coordinates oldPos, char value): void
    + Map_get_case(Coordinates pos): char
}


class Treasure {
    - position_x: int
    - position_y: int
    + Treasure_init(): void
    + Treasure_get_pos(): Coordinates
}

class Pirate{
    - position_x: int
    - position_y: int
    + Pirate_init(): void
    + Pirate_is_on_player(Coordinates pos_player): bool
    + Pirate_see_player(Coordinates pos): Pirate_state_t
    - Pirate_movement(direction_t dir): bool
}

class Trap{
    - position_x: int
    - position_y: int
    - numTrap: int
    + Trap_get_pos(Trap * trap): Coordinates
    + Trap_get_number(Trap * trap): int
    + Trap_new(): Trap *
    + Trap_delete(Trap * this): void
}


@enduml